
import React from 'react';
import { 
  LayoutDashboard, 
  IndianRupee, 
  AlertCircle, 
  Users, 
  UserCircle,
  FileText,
  Clock
} from 'lucide-react';

export const NAV_ITEMS = [
  { id: 'dashboard', labelKey: 'nav_home', icon: <LayoutDashboard size={20} /> },
  { id: 'income', labelKey: 'nav_earnings', icon: <IndianRupee size={20} /> },
  { id: 'notes', labelKey: 'nav_notes', icon: <FileText size={20} /> },
  { id: 'sos', labelKey: 'nav_sos', icon: <AlertCircle size={20} className="text-red-500" /> },
  { id: 'community', labelKey: 'nav_drivehub', icon: <Users size={20} /> },
  { id: 'profile', labelKey: 'nav_account', icon: <UserCircle size={20} /> },
];

export const INCOME_CATEGORIES = ['Ride Hail', 'Delivery', 'Private Client', 'Tips', 'Bonus'];
export const EXPENSE_CATEGORIES = ['Fuel', 'Maintenance', 'Insurance', 'Food', 'Misc'];

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  'English': {
    nav_home: 'Home',
    nav_earnings: 'Earnings',
    nav_notes: 'Notes',
    nav_sos: 'SOS',
    nav_drivehub: 'DriveHub',
    nav_account: 'Account',
    welcome: 'Hello',
    ready: 'Ready for the road today?',
    profit_today: "Today's Profit",
    expense_today: "Today's Expense",
    quick_actions: 'Quick Actions',
    add_income: 'Add Income',
    add_expense: 'Add Expense',
    voice_ai: 'Voice AI',
    car_check: 'Car Check',
    health: 'Health',
    emergency_sos: 'Emergency SOS',
    recent_updates: 'DriveHub Updates',
    view_all: 'View All',
    pro_tip: 'Daily Pro Tip',
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    language: 'Language',
    subscription: 'Subscription Plan',
    notifications: 'Notifications',
    sign_out: 'Sign Out',
    history: 'History',
    weekly_total: 'Weekly Total',
    manage_cats: 'Manage Categories',
    source_name: 'Source Name',
    amount: 'Amount',
    category: 'Category',
    notes_header: 'My Notes',
    notes_sub: 'Capture thoughts & reminders',
    new_note: 'New Note',
    save_note: 'Save Note',
    sos_hub: 'SOS Hub',
    connected_drivers: 'Connected Drivers',
    responsive: 'Responsive',
    recording_alert: 'Recording Alert',
    broadcast: 'Broadcast',
    voice_alert: 'Voice Alert',
    join_drivers: 'drivers online',
    top_driver: 'Top Driver of the Week',
    all_feed: 'All Feed',
    nearby: 'Nearby',
    tech_tips: 'Tech Tips',
    create_post: 'Create Post',
    post: 'Post',
    professional_driver: 'Professional Driver',
    backup_restore: 'Backup & Restore',
    sync_cloud: 'Sync with Cloud',
    privacy_security: 'Privacy & Security',
    support_center: 'Support Center',
    premium_unlock: 'Upgrade for full features',
    rating: 'Rating',
    edit_note: 'Edit Note',
    alarms: 'Alarms',
    add_alarm: 'Add Alarm',
    wake_up: 'Wake Up',
    sleep_time: 'Sleep Time',
    rest_break: 'Rest Break',
    screen_time: 'Screen Time',
    alarm_set: 'Alarm Set Successfully',
    dark_mode: 'Dark Mode',
    theme: 'App Theme'
  },
  'Hindi (हिन्दी)': {
    nav_home: 'होम',
    nav_earnings: 'कमाई',
    nav_notes: 'नोट्स',
    nav_sos: 'एसओएस',
    nav_drivehub: 'ड्राइवहब',
    nav_account: 'खाता',
    welcome: 'नमस्ते',
    ready: 'आज सड़क के लिए तैयार हैं?',
    profit_today: 'आज का लाभ',
    expense_today: 'आज का खर्च',
    quick_actions: 'त्वरित कार्रवाई',
    add_income: 'आय जोड़ें',
    add_expense: 'खर्च जोड़ें',
    voice_ai: 'वॉयस एआई',
    car_check: 'कार चेक',
    health: 'स्वास्थ्य',
    emergency_sos: 'आपातकालीन एसओएस',
    recent_updates: 'ड्राइवहब अपडेट',
    view_all: 'सभी देखें',
    pro_tip: 'दैनिक प्रो टिप',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    edit: 'संपादित करें',
    delete: 'हटाएं',
    language: 'भाषा',
    subscription: 'सदस्यता योजना',
    notifications: 'सूचनाएं',
    sign_out: 'साइन आउट',
    history: 'इतिहास',
    weekly_total: 'साप्ताहिक कुल',
    manage_cats: 'श्रेणियां प्रबंधित करें',
    source_name: 'स्रोत का नाम',
    amount: 'राशि',
    category: 'श्रेणी',
    notes_header: 'मेरे नोट्स',
    notes_sub: 'विचारों और रिमाइंडर्स को सहेजें',
    new_note: 'नया नोट',
    save_note: 'नोट सहेजें',
    sos_hub: 'एसओएस हब',
    connected_drivers: 'जुड़े हुए ड्राइवर',
    responsive: 'उत्तरदायी',
    recording_alert: 'रिकॉर्डिंग अलर्ट',
    broadcast: 'प्रसारण',
    voice_alert: 'वॉयस अलर्ट',
    join_drivers: 'ड्राइवर ऑनलाइन हैं',
    top_driver: 'सप्ताह का सर्वश्रेष्ठ ड्राइवर',
    all_feed: 'सभी फ़ीड',
    nearby: 'पास के',
    tech_tips: 'टेक टिप्स',
    create_post: 'पोस्ट बनाएं',
    post: 'भेजें',
    professional_driver: 'पेशेवर ड्राइवर',
    backup_restore: 'बैकअप और रिस्टोर',
    sync_cloud: 'क्लाउड के साथ सिंक करें',
    privacy_security: 'गोपनीयता और सुरक्षा',
    support_center: 'सहायता केंद्र',
    premium_unlock: 'पूर्ण सुविधाओं के लिए अपग्रेड करें',
    rating: 'रेटिंग',
    edit_note: 'नोट संपादित करें',
    alarms: 'अलार्म',
    add_alarm: 'अलार्म जोड़ें',
    wake_up: 'जागना',
    sleep_time: 'सोने का समय',
    rest_break: 'आराम का समय',
    screen_time: 'स्क्रीन टाइम',
    alarm_set: 'अलार्म सफलतापूर्वक सेट किया गया',
    dark_mode: 'डार्क मोड',
    theme: 'ऐप थीम'
  },
  'Marathi (मराठी)': {
    nav_home: 'होम',
    nav_earnings: 'कमाई',
    nav_notes: 'नोट्स',
    nav_sos: 'एसओएस',
    nav_drivehub: 'ड्राइव्हहब',
    nav_account: 'खाते',
    welcome: 'नमस्कार',
    ready: 'आज रस्त्यासाठी तयार आहात?',
    profit_today: 'आजचा नफा',
    expense_today: 'आजचा खर्च',
    quick_actions: 'द्रुत कृती',
    add_income: 'उत्पन्न जोडा',
    add_expense: 'खर्च जोडा',
    voice_ai: 'व्हॉइस एआय',
    car_check: 'कार चेक',
    health: 'आरोग्य',
    emergency_sos: 'आणीबाणी एसओएस',
    recent_updates: 'ड्राइव्हहब अपडेट्स',
    view_all: 'सर्व पहा',
    pro_tip: 'दैनिक प्रो टिप',
    save: 'जतन करा',
    cancel: 'रद्द करा',
    edit: 'संपादित करा',
    delete: 'काढून टाका',
    language: 'भाषा',
    subscription: 'सबस्क्रिप्शन प्लॅन',
    notifications: 'सूचना',
    sign_out: 'साइन आउट',
    history: 'इतिहास',
    weekly_total: 'साप्ताहिक एकूण',
    manage_cats: 'श्रेणी व्यवस्थापित करा',
    source_name: 'स्रोताचे नाव',
    amount: 'रक्कम',
    category: 'श्रेणी',
    notes_header: 'माझे नोट्स',
    notes_sub: 'विचार आणि स्मरणपत्रे जतन करा',
    new_note: 'नवीन नोट',
    save_note: 'नोट जतन करा',
    sos_hub: 'एसओएस हब',
    connected_drivers: 'कनेक्ट केलेले ड्रायव्हर',
    responsive: 'प्रतिसाद देणारा',
    recording_alert: 'रेकॉर्डिंग अलर्ट',
    broadcast: 'ब्रॉडकास्ट',
    voice_alert: 'व्हॉइस अलर्ट',
    join_drivers: 'ड्रायव्हर ऑनलाइन आहेत',
    top_driver: 'आवडता ड्रायव्हर',
    all_feed: 'सर्व फीड',
    nearby: 'जवळपास',
    tech_tips: 'टेक टिप्स',
    create_post: 'पोस्ट तयार करा',
    post: 'पोस्ट करा',
    professional_driver: 'व्यावसायिक ड्रायव्हर',
    backup_restore: 'बॅकअप आणि रिस्टोर',
    sync_cloud: 'क्लाउडसह सिंक करा',
    privacy_security: 'गोपनीयता आणि सुरक्षा',
    support_center: 'सहाय्य केंद्र',
    premium_unlock: 'पूर्ण वैशिष्ट्यांसाठी अपग्रेड करा',
    rating: 'रेटिंग',
    edit_note: 'नोट संपादित करा',
    alarms: 'अलार्म',
    add_alarm: 'अलार्म जोडा',
    wake_up: 'जागणे',
    sleep_time: 'झोपण्याची वेळ',
    rest_break: 'विश्रांती',
    screen_time: 'स्क्रीन वेळ',
    alarm_set: 'अलार्म यशस्वीरित्या सेट केला',
    dark_mode: 'डार्क मोड',
    theme: 'अॅप थीम'
  }
};

export const t = (key: string, language: string) => {
  return TRANSLATIONS[language]?.[key] || TRANSLATIONS['English'][key] || key;
};
